[tool.poetry]
name = "angle-estimation"
version = "0.1.0"
description = ""
authors = ["Francisco-SP3 <A01177893@tec.mx>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
mediapipe = "^0.10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
